name: Mirror to Public Repo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push main to public mirror
        env:
          MIRROR_URL: https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/wslu42/hubkochab-canvas-mirror.git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add mirror "$MIRROR_URL"
          git push -f mirror main:main
