name: Mirror to Public

on:
  push:
    branches: [ main ]   # adjust if needed
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for --mirror

      - name: Push --mirror to public repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add public https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/wslu42/hubkochab-canvas-mirror.git
          # Push EVERYTHING (branches, tags). Remove --mirror if you only want main.
          git push --force --mirror public
